---
title: "QuantAQ Missing Data Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, echo=FALSE, message=FALSE, warning=FALSE}
### load packages 

library(QuantAQAPIClient)
library(here) 
library(lubridate) 
library(tictoc)
library(DT)
library(purrr)
library(tidyverse)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
### Connect to QuantAQ API (necessary to obtain data)

setup_client() #log in to QuantAQ account and click developer in the left menu to grab API key
```

```{r devices, echo=FALSE, message=FALSE, warning=FALSE}
### create lists of devices by country 

uganda_devices <- c("MOD-PM-00844", "MOD-PM-00847", "MOD-PM-00831", "MOD-PM-00846", "MOD-PM-00832",
                     "MOD-PM-00845", "MOD-PM-00828", "MOD-PM-00826", "MOD-PM-00838", "MOD-00117",
                     "MOD-PM-00836")


kenya_devices <- c("MOD-PM-00852", "MOD-PM-00834", "MOD-PM-00830", "MOD-PM-00840", "MOD-PM-00843",
                    "MOD-PM-00841", "MOD-PM-00849", "MOD-PM-00850", "MOD-PM-00848", "MOD-PM-00829",
                    "MOD-00116")


ethiopia_devices <- c("MOD-PM-00827", "MOD-PM-00839", "MOD-PM-00842", "MOD-PM-00833", "MOD-PM-00855",
                    "MOD-PM-00854", "MOD-PM-00835", "MOD-PM-00837", "MOD-PM-00851", "MOD-00118",
                    "MOD-PM-00853")


ghana_devices <- c("MOD-PM-01054", "MOD-PM-00900", "MOD-PM-00876", "MOD-PM-00882", "MOD-PM-00896",
                    "MOD-PM-00897", "MOD-PM-00892", "MOD-PM-00877", "MOD-PM-01060", "MOD-PM-01055",
                    "MOD-PM-00884", "MOD-PM-01056", "MOD-PM-01051", "MOD-PM-01059", "MOD-PM-00881",
                    "MOD-PM-00891", "MOD-PM-00898", "MOD-PM-01052", "MOD-00400", "MOD-PM-00894",
                    "MOD-PM-01053", "MOD-PM-00887", "MOD-PM-00886", "MOD-PM-00879", "MOD-PM-00890",
                    "MOD-PM-00889", "MOD-PM-00899", "MOD-PM-00883", "MOD-PM-00895", "MOD-PM-01057",
                    "MOD-PM-01058", "MOD-PM-00893", "MOD-PM-00878", "MOD-PM-00888", "MOD-PM-00885",
                    "MOD-00398", "MOD-00401", "MOD-00399", "MOD-00397", "MOD-PM-00880")

#ghana_devices <- c("MOD-00398", "MOD-00401", "MOD-00399", "MOD-00397","MOD-00400")
```

#### For all tables, each cell represents the number of hours a device was inactive during a day. An hour was classified as inactive/missing if there were less than 30 observations during the hour.

## Uganda Devices

```{r uganda, echo=FALSE, message=FALSE, warning=FALSE}
Sys.setenv(TZ = 'Africa/Kampala') #EAT for kenya, uganda, ethiopia 
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Define start_date and end_date
start_date <- as.Date("2024-06-01") ## DUE TO TIMEZONES, START DATE NEEDS TO BE 1 DAY BEFORE THE ACTUAL START DATE OF INTEREST

end_date <- as.Date("2024-06-10")

country = "Uganda" #for adding country row to final table

# List of device serial numbers
device_list <- uganda_devices

# Initialize an empty list to store results for each device
result_combined <- list()

# Loop through each device in the device list
for (device in device_list) {
  
  # Function to get data by date, handling errors
  get_data_safe <- possibly(get_data_by_date, otherwise = NULL)
  
  # Use map to get data for each date, handling errors
  result_list <- map(seq(start_date, end_date, by = "days"), function(date) {
    formatted_date <- format(date, "%Y-%m-%d")
    get_data_safe(sn = device, date = formatted_date)
  })
  
  # Filter out NULL elements (empty lists)
  result_list <- purrr::discard(result_list, ~ is.null(.x) || length(.x) == 0)
  
  if (!is_empty(result_list)) {
  # Combine the list of data frames into a single data frame
  result_df <- do.call(bind_rows, lapply(result_list, as.data.frame)) %>%
    mutate(monitor = device) %>%
    select(monitor, everything()) %>%
    mutate(timestamp = as.POSIXct(timestamp)) %>% 
    mutate(timestamp = format(timestamp, "%Y-%m-%d %H:%M")) %>% 
    mutate(timestamp = lubridate::ymd_hm(timestamp)) %>%
    mutate(local_timestamp = timestamp + hours(3))
  
  #create data frame with just the time range of interest
  minutely_df <- data.frame(timestamp = seq.POSIXt(
    as.POSIXct(start_date, tz = "UTC"),
    as.POSIXct(end_date + 1, tz = "UTC"),
    by = "min"
  )) %>%
    mutate(local_timestamp = timestamp + hours(3)) #time stamp is in GMT, so adding 3 hours to match EAT. 
  
  #join the empty time stamp data frame to the downloaded data from QuantAQ
  result_df_full <- full_join(result_df, minutely_df) %>% 
    arrange(timestamp) %>%
    mutate(date = as.Date(local_timestamp)) %>%  
    mutate(hour = hour(ymd_hms(local_timestamp))) %>%
    mutate(monitor = device) %>%
    select(monitor, timestamp, local_timestamp, date, hour, everything()) 
  
  # Store the result for the current device in the combined list
  result_combined[[device]] <- result_df_full
  } else {
    # If there's no data for this device, create an empty dataframe
    minutely_df_empty <- data.frame(timestamp = seq.POSIXt(
      as.POSIXct(start_date, tz = "UTC"),
      as.POSIXct(end_date + 1, tz = "UTC"),
      by = "min"
    )) %>%
    mutate(local_timestamp = timestamp + hours(3))
    
    #format minutely_df_empty to have the monitor info and day/hour variables at local time
    minutely_df_empty <- minutely_df_empty %>% mutate(date = as.Date(local_timestamp)) %>%  
      mutate(hour = hour(ymd_hms(local_timestamp))) %>%
      mutate(monitor = device) %>%
      select(monitor, timestamp, local_timestamp, date, hour) 
      
    result_combined[[device]] <- minutely_df_empty
  }
}

# Combine data for all devices into a single data frame
final_result_df <- bind_rows(result_combined)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#create table of missing data 
final_result_df %>%
  filter(date <= as.Date(end_date),
         date > as.Date(start_date)) %>%
  group_by(date, hour, monitor) %>%
  summarise(no_data = sum(is.na(pm25))) %>%
  mutate(missing_hour = ifelse(no_data > 30, 1, 0)) %>% #missing hour classified if more than 30 observations are missing in an hour
  ungroup() %>%
  group_by(date, monitor) %>%
  summarise(hours_missing_day = sum(missing_hour)) %>%
  pivot_wider(names_from = date, values_from = hours_missing_day) %>%
  mutate(country = country) %>%
  select(monitor, country, everything()) %>%
  datatable()
```

## Kenya Devices

```{r kenya, echo=FALSE, message=FALSE, warning=FALSE}
Sys.setenv(TZ = 'Africa/Kampala') #EAT for kenya, uganda, ethiopia 
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Define start_date and end_date
start_date <- as.Date("2024-06-01") ## DUE TO TIMEZONES, START DATE NEEDS TO BE 1 DAY BEFORE THE ACTUAL START DATE OF INTEREST

end_date <- as.Date("2024-06-10")

country = "Kenya"

# List of device serial numbers
device_list <- kenya_devices

# Initialize an empty list to store results for each device
result_combined <- list()

# Loop through each device in the device list
for (device in device_list) {
  # Function to get data by date, handling errors
  get_data_safe <- possibly(get_data_by_date, otherwise = NULL)
  
  # Use map to get data for each date, handling errors
  result_list <- map(seq(start_date, end_date, by = "days"), function(date) {
    formatted_date <- format(date, "%Y-%m-%d")
    get_data_safe(sn = device, date = formatted_date)
  })
  
  # Filter out NULL elements (empty lists)
  result_list <- purrr::discard(result_list, ~ is.null(.x) || length(.x) == 0)
  
  if (!is_empty(result_list)) {
  # Combine the list of data frames into a single data frame
  result_df <- do.call(bind_rows, lapply(result_list, as.data.frame)) %>%
    mutate(monitor = device) %>%
    select(monitor, everything()) %>%
    mutate(timestamp = as.POSIXct(timestamp)) %>% 
    mutate(timestamp = format(timestamp, "%Y-%m-%d %H:%M")) %>% 
    mutate(timestamp = lubridate::ymd_hm(timestamp)) %>%
    mutate(local_timestamp = timestamp + hours(3)) #time stamp is in GMT, so adding 3 hours to match EAT. 
  
  minutely_df <- data.frame(timestamp = seq.POSIXt(
    as.POSIXct(start_date, tz = "UTC"),
    as.POSIXct(end_date + 1, tz = "UTC"),
    by = "min"
  )) %>%
    mutate(local_timestamp = timestamp + hours(3))
  
  result_df_full <- full_join(result_df, minutely_df) %>% 
    arrange(timestamp) %>%
    mutate(date = as.Date(local_timestamp)) %>%  
    mutate(hour = hour(ymd_hms(local_timestamp))) %>%
    mutate(monitor = device) %>%
    select(monitor, timestamp, local_timestamp, date, hour, everything()) 
  
  # Store the result for the current device in the combined list
  result_combined[[device]] <- result_df_full
  } else {
    # If there's no data for this device, create an empty dataframe
    minutely_df_empty <- data.frame(timestamp = seq.POSIXt(
      as.POSIXct(start_date, tz = "UTC"),
      as.POSIXct(end_date + 1, tz = "UTC"),
      by = "min"
    )) %>%
    mutate(local_timestamp = timestamp + hours(3))
    
    minutely_df_empty <- minutely_df_empty %>% mutate(date = as.Date(local_timestamp)) %>%  
      mutate(hour = hour(ymd_hms(local_timestamp))) %>%
      mutate(monitor = device) %>%
      select(monitor, timestamp, local_timestamp, date, hour) 
      
    result_combined[[device]] <- minutely_df_empty
  }
}

# Combine data for all devices into a single data frame
final_result_df <- bind_rows(result_combined)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
final_result_df %>%
  filter(date <= as.Date(end_date),
         date > as.Date(start_date)) %>%
  group_by(date, hour, monitor) %>%
  summarise(no_data = sum(is.na(pm25))) %>%
  mutate(missing_hour = ifelse(no_data > 30, 1, 0)) %>% #missing hour classified if more than 30 observations are missing in an hour
  ungroup() %>%
  group_by(date, monitor) %>%
  summarise(hours_missing_day = sum(missing_hour)) %>%
  pivot_wider(names_from = date, values_from = hours_missing_day) %>%
  mutate(country = country) %>%
  select(monitor, country, everything()) %>%
  datatable()
```

## Ethiopia Devices

```{r ethiopia, echo=FALSE, message=FALSE, warning=FALSE}
Sys.setenv(TZ = 'Africa/Kampala') #EAT for kenya, uganda, ethiopia 
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Define start_date and end_date
start_date <- as.Date("2024-06-01") ## DUE TO TIMEZONES, START DATE NEEDS TO BE 1 DAY BEFORE THE ACTUAL START DATE OF INTEREST

end_date <- as.Date("2024-06-10")


country = "Ethiopia"

# List of device serial numbers
device_list <- ethiopia_devices

# Initialize an empty list to store results for each device
result_combined <- list()

# Loop through each device in the device list
for (device in device_list) {
  # Function to get data by date, handling errors
  get_data_safe <- possibly(get_data_by_date, otherwise = NULL)
  
  # Use map to get data for each date, handling errors
  result_list <- map(seq(start_date, end_date, by = "days"), function(date) {
    formatted_date <- format(date, "%Y-%m-%d")
    get_data_safe(sn = device, date = formatted_date)
  })
  
  # Filter out NULL elements (empty lists)
  result_list <- purrr::discard(result_list, ~ is.null(.x) || length(.x) == 0)
  
  if (!is_empty(result_list)) {
  # Combine the list of data frames into a single data frame
  result_df <- do.call(bind_rows, lapply(result_list, as.data.frame)) %>%
    mutate(monitor = device) %>%
    select(monitor, everything()) %>%
    mutate(timestamp = as.POSIXct(timestamp)) %>% 
    mutate(timestamp = format(timestamp, "%Y-%m-%d %H:%M")) %>% 
    mutate(timestamp = lubridate::ymd_hm(timestamp)) %>%
    mutate(local_timestamp = timestamp + hours(3)) #time stamp is in GMT, so adding 3 hours to match EAT. 
  
  minutely_df <- data.frame(timestamp = seq.POSIXt(
    as.POSIXct(start_date, tz = "UTC"),
    as.POSIXct(end_date + 1, tz = "UTC"),
    by = "min"
  )) %>%
    mutate(local_timestamp = timestamp + hours(3))
  
  result_df_full <- full_join(result_df, minutely_df) %>% 
    arrange(timestamp) %>%
    mutate(date = as.Date(local_timestamp)) %>%  
    mutate(hour = hour(ymd_hms(local_timestamp))) %>%
    mutate(monitor = device) %>%
    select(monitor, timestamp, local_timestamp, date, hour, everything()) 
  
  # Store the result for the current device in the combined list
  result_combined[[device]] <- result_df_full
  } else {
    # If there's no data for this device, create an empty dataframe
    minutely_df_empty <- data.frame(timestamp = seq.POSIXt(
      as.POSIXct(start_date, tz = "UTC"),
      as.POSIXct(end_date + 1, tz = "UTC"),
      by = "min"
    )) %>%
    mutate(local_timestamp = timestamp + hours(3))
    
    minutely_df_empty <- minutely_df_empty %>% mutate(date = as.Date(local_timestamp)) %>%  
      mutate(hour = hour(ymd_hms(local_timestamp))) %>%
      mutate(monitor = device) %>%
      select(monitor, timestamp, local_timestamp, date, hour) 
      
    result_combined[[device]] <- minutely_df_empty
  }
}

# Combine data for all devices into a single data frame
final_result_df <- bind_rows(result_combined)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
final_result_df %>%
  filter(date <= as.Date(end_date),
         date > as.Date(start_date)) %>%
  group_by(date, hour, monitor) %>%
  summarise(no_data = sum(is.na(pm25))) %>%
  mutate(missing_hour = ifelse(no_data > 30, 1, 0)) %>% #missing hour classified if more than 30 observations are missing in an hour
  ungroup() %>%
  group_by(date, monitor) %>%
  summarise(hours_missing_day = sum(missing_hour)) %>%
  pivot_wider(names_from = date, values_from = hours_missing_day) %>%
  mutate(country = country) %>%
  select(monitor, country, everything()) %>%
  datatable()
```

## Ghana Devices

```{r, echo=FALSE, message=FALSE, warning=FALSE}
Sys.setenv(TZ = 'Africa/Accra') #GMT for Ghana
```

```{r ghana, echo=FALSE, message=FALSE, warning=FALSE}
# Define start_date and end_date
start_date <- as.Date("2024-06-08") ## DUE TO TIMEZONES, START DATE NEEDS TO BE 1 DAY BEFORE THE ACTUAL START DATE OF INTEREST

end_date <- as.Date("2024-07-05")


country = "Ghana"

# List of device serial numbers
device_list <- ghana_devices

# Initialize an empty list to store results for each device
result_combined <- list()

# Loop through each device in the device list
for (device in device_list) {
  # Function to get data by date, handling errors
  get_data_safe <- possibly(get_data_by_date, otherwise = NULL)
  
  # Use map to get data for each date, handling errors
  result_list <- map(seq(start_date, end_date, by = "days"), function(date) {
    formatted_date <- format(date, "%Y-%m-%d")
    get_data_safe(sn = device, date = formatted_date)
  })
  
  # Filter out NULL elements (empty lists)
  result_list <- purrr::discard(result_list, ~ is.null(.x) || length(.x) == 0)
  
  if (!is_empty(result_list)) {
  # Combine the list of data frames into a single data frame
  result_df <- do.call(bind_rows, lapply(result_list, as.data.frame)) %>%
    mutate(monitor = device) %>%
    select(monitor, everything()) %>%
    mutate(timestamp = as.POSIXct(timestamp)) %>% 
    mutate(timestamp = format(timestamp, "%Y-%m-%d %H:%M")) %>% 
    mutate(timestamp = lubridate::ymd_hm(timestamp)) %>%
    mutate(local_timestamp = timestamp) #local timestamp is the same as the timestamp variable for Ghana (GMT) 
  
  minutely_df <- data.frame(timestamp = seq.POSIXt(
    as.POSIXct(start_date, tz = "UTC"),
    as.POSIXct(end_date + 1, tz = "UTC"),
    by = "min"
  )) %>%
    mutate(local_timestamp = timestamp)
  
  result_df_full <- full_join(result_df, minutely_df) %>% 
    arrange(timestamp) %>%
    mutate(date = as.Date(local_timestamp)) %>%  
    mutate(hour = hour(ymd_hms(local_timestamp))) %>%
    mutate(monitor = device) %>%
    select(monitor, timestamp, local_timestamp, date, hour, everything()) 
  
  # Store the result for the current device in the combined list
  result_combined[[device]] <- result_df_full
  } else {
    # If there's no data for this device, create an empty dataframe
    minutely_df_empty <- data.frame(timestamp = seq.POSIXt(
      as.POSIXct(start_date, tz = "UTC"),
      as.POSIXct(end_date + 1, tz = "UTC"),
      by = "min"
    )) %>%
    mutate(local_timestamp = timestamp)
    
    minutely_df_empty <- minutely_df_empty %>% mutate(date = as.Date(local_timestamp)) %>%  
      mutate(hour = hour(ymd_hms(local_timestamp))) %>%
      mutate(monitor = device) %>%
      select(monitor, timestamp, local_timestamp, date, hour) 
      
    result_combined[[device]] <- minutely_df_empty
  }
}

# Combine data for all devices into a single data frame
final_result_df <- bind_rows(result_combined)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
final_result_df %>%
  filter(date <= as.Date(end_date),
         date > as.Date(start_date)) %>%
  group_by(date, hour, monitor) %>%
  summarise(no_data = sum(is.na(pm25))) %>%
  mutate(missing_hour = ifelse(no_data > 30, 1, 0)) %>% #missing hour classified if more than 30 observations are missing in an hour
  ungroup() %>%
  group_by(date, monitor) %>%
  summarise(hours_missing_day = sum(missing_hour)) %>%
  pivot_wider(names_from = date, values_from = hours_missing_day) %>%
  mutate(country = country) %>%
  select(monitor, country, everything()) %>%
  datatable()
```


```{r}
colorful_table <- final_result_df %>%
  filter(date <= as.Date(end_date),
         date > as.Date(start_date)) %>%
  group_by(date, hour, monitor) %>%
  summarise(no_data = sum(is.na(pm25))) %>%
  mutate(missing_hour = ifelse(no_data > 30, 1, 0)) %>%
  ungroup() %>%
  group_by(date, monitor) %>%
  summarise(hours_missing_day = sum(missing_hour)) %>%
  pivot_wider(names_from = date, values_from = hours_missing_day) %>%
  mutate(country = country) %>%
  select(monitor, country, everything())


# Identify numeric columns
numeric_cols <- names(colorful_table)[sapply(colorful_table, is.numeric)]

colorful_table %>%
  datatable(options = list(stripe = FALSE)) %>%
  formatStyle(
    numeric_cols,  # Apply formatting to all numeric columns
    backgroundColor = styleInterval(12, c("white", "#fae6e6"))
  )

```

